# Generated by Django 3.2 on 2021-04-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigaa_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
    ]
